services:
  db:
    image: mariadb:11.2.2
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./docker/mariadb/data:/var/lib/mariadb"
    ports:
      - "3306:3306"
    healthcheck:
      test: "healthcheck.sh --su-mysql --connect --innodb_initialized"
      interval: 1m
      timeout: 20s
      retries: 10
      start_period: 20s

  express:
    build:
      context: .
      target: api
    environment:
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      NODE_ENV: development
    healthcheck:
      test: "curl -f http://localhost:3000/ || exit 1"
      interval: 1m
      timeout: 20s
      retries: 10
      start_period: 20s

    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ".:/app"
    command: ["npm", "run", "dev"]

  adminer:
    image: adminer
    ports:
      - 8080:8080
